<?php
$cpt = array(
	array('id' => 'public',
		'type' => 'checkbox',
		'label' => 'Public',
		'desc' => 'Публичный или используется только технически',
		'data-hide' => 'publicly_queryable, show_ui'
		),
	array('id' => 'publicly_queryable',
		'type' => 'checkbox',
		'label' => 'Publicly queryable',
		'desc' => 'Показывать во front\'е',
		),
	array('id' => 'show_ui',
		'type' => 'checkbox',
		'label' => 'Show UI',
		'desc' => 'Показывать управление типом записи',
		),
	array('id' => 'show_in_menu',
		'type' => 'checkbox',
		'label' => 'Show in Menu',
		'desc' => 'Показывать ли в админ-меню',
		),
	array('id' => 'rewrite',
		'type' => 'checkbox',
		'label' => 'ReWrite',
		'desc' => 'ЧПУ',
		'default' => 'on'
		),
	array('id' => 'has_archive',
		'type' => 'checkbox',
		'label' => 'Has archive',
		'desc' => 'Поддержка архивной страницы',
		),
	array('id' => 'hierarchical',
		'type' => 'checkbox',
		'label' => 'Hierarchical',
		'desc' => 'Родители / тексономии',
		),
	array('id' => 'query_var',
		'type' => 'text',
		'label' => 'Query var',
		'desc' => '$post_type в query_var',
		),
	array('id' => 'capability_type',
		'type' => 'text',
		'label' => 'Capability as',
		'desc' => 'Права такие же как..',
		'default' => 'post'
		),
	array('id' => 'menu_position',
		'type' => 'number',
		'label' => 'Menu position',
		'desc' => '',
		),
	array('id' => 'menu_icon',
		'type' => 'text',
		'label' => 'Menu icon',
		'default' => 'dashicons-admin-post',
		)
	);

return $cpt;